# Generated by Django 4.2 on 2023-04-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=30)),
                ('full_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
